var fs = require('fs');

var buildPostmanImport = function() {
  for (i=0; i<endpoints.length; i++) {

    var endpointShape = {
      "name": "",
      "request": {
        "url": "",
        "method": "",
        "header": [],
        "body": {},
        "description": ""
      },
      "response": []
    }

    endpointShape["name"] = endpoints[i].endpoint
    endpointShape["request"]["url"] = "https://portal.opendmc.org/rest"+endpoints[i].endpoint
    endpointShape["request"]["method"] = endpoints[i].method ? endpoints[i].method : "GET"

    postmanImport["item"].push(endpointShape)
  }

  return postmanImport
}


var postmanImport = {
	"variables": [],
	"info": {
		"name": "PostmanImport",
		"_postman_id": "0266b793-8efc-b01d-66fc-e98098fcc985",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": [
	]
}

var endpoints = [
  {
    endpoint:"/companies"
  },
  {
    method: "POST",
    endpoint:"/accountNotificationCategories"
  }
  // {
  //   endpoint:"/account-notification-settings/"
  // },
  // {
  //   endpoint:"/account_servers"
  // },
  // {
  //   endpoint:"/accounts/"
  // },
  // {
  //   endpoint:"/companies"
  // },
  // {
  //   endpoint:"/companies"
  // },
  // {
  //   endpoint:"/companies"
  // },
  // {
  //   endpoint:"/accountNotificationCategories"
  // },
  // {
  //   endpoint:"/account-notification-settings/"
  // },
  // {
  //   endpoint:"/account_servers"
  // },
  // {
  //   endpoint:"/accounts/"
  // },
  // {
  //   endpoint:"/announcements"
  // },
  // {
  //   endpoint:"/appSubmission"
  // },
  // {
  //   endpoint:"/appSubmission/appName"
  // },
  // {
  //   endpoint:"/assign_users"
  // },
  // {
  //   endpoint:"/error"
  // },
  // {
  //   endpoint:"/companies/create"
  // },
  // {
  //   endpoint:"/company/follow"
  // },
  // {
  //   endpoint:"/company/unfollow/"
  // },
  // {
  //   endpoint:"/company_reviews"
  // },
  // {
  //   endpoint:"/company_featured/add"
  // },
  // {
  //   endpoint:"/company_featured/"
  // },
  // {
  //   endpoint:"/company_key_contacts"
  // },
  // {
  //   endpoint:"/company_reviews_flagged"
  // },
  // {
  //   endpoint:"/company_reviews_helpful"
  // },
  // {
  //   endpoint:"/company_skills"
  // },
  // {
  //   endpoint:"/compare_services"
  // },
  // {
  //   endpoint:"/directories"
  // },
  // {
  //   endpoint:"/all-discussions"
  // },
  // {
  //   endpoint:"/discussions/create"
  // },
  // {
  //   endpoint:"/dmdiidocument"
  // },
  // {
  //   endpoint:"/dmdiidocument/filetype"
  // },
  // {
  //   endpoint:"/dmdiidocuments"
  // },
  // {
  //   endpoint:"/dmdiidocuments/dmdiiProjectId"
  // },
  // {
  //   endpoint:"/dmdiidocuments/getAllTags"
  // },
  // {
  //   endpoint:"/dmdiidocuments/saveDocumentTag"
  // },
  // {
  //   endpoint:"/staticdocument/"
  // },
  // {
  //   endpoint:"/dmdiiMember"
  // },
  // {
  //   endpoint:"/dmdiiMember/all"
  // },
  // {
  //   endpoint:"/dmdiiMember/events"
  // },
  // {
  //   endpoint:"/dmdiiMember/mapEntry"
  // },
  // {
  //   endpoint:"/dmdiiMember/news"
  // },
  // {
  //   endpoint:"/dmdiiMember/save"
  // },
  // {
  //   endpoint:"/dmdiiMember/search"
  // },
  // {
  //   endpoint:"/dmdiiportalimage"
  // },
  // {
  //   endpoint:"/contributingCompanies"
  // },
  // {
  //   endpoint:"/dmdiiProject/events"
  // },
  // {
  //   endpoint:"/dmdiiProject/news"
  // },
  // {
  //   endpoint:"/dmdiiProject/save"
  // },
  // {
  //   endpoint:"/dmdiiProject/"
  // },
  // {
  //   endpoint:"/dmdiiProjectUpdate"
  // },
  // {
  //   endpoint:"/dmdiiProjects/"
  // },
  // {
  //   endpoint:"/dmdiiproject/contributingcompanies"
  // },
  // {
  //   endpoint:"/dmdiiprojects"
  // },
  // {
  //   endpoint:"/dmdiiprojects/awardDate"
  // },
  // {
  //   endpoint:"/dmdiiprojects/member"
  // },
  // {
  //   endpoint:"/dmdiiprojects/member/active"
  // },
  // {
  //   endpoint:"/dmdiiprojects/search"
  // },
  // {
  //   endpoint:"/dmdiiquicklink"
  // },
  // {
  //   endpoint:"/dmdiiType"
  // },
  // {
  //   endpoint:"/documents"
  // },
  // {
  //   endpoint:"/documents/clone"
  // },
  // {
  //   endpoint:"/documents/directories/"
  // },
  // {
  //   endpoint:"/documents/tags"
  // },
  // {
  //   endpoint:"/documents/versions/"
  // },
  // {
  //   endpoint:"/getChildren"
  // },
  // {
  //   endpoint:"/getModel"
  // },
  // {
  //   endpoint:"/dome-interfaces"
  // },
  // {
  //   endpoint:"/events"
  // },
  // {
  //   endpoint:"/faq_articles"
  // },
  // {
  //   endpoint:"/faq_categories"
  // },
  // {
  //   endpoint:"/faq_subcategories"
  // },
  // {
  //   endpoint:"/favorite_products"
  // },
  // {
  //   endpoint:"/follow_discussions"
  // },
  // {
  //   endpoint:"/follow_people_discussions"
  // },
  // {
  //   endpoint:"/following_discussions"
  // },
  // {
  //   endpoint:"/following_members"
  // },
  // {
  //   endpoint:"/individual-discussion-comments"
  // },
  // {
  //   endpoint:"/individual-discussion-comments-flagged"
  // },
  // {
  //   endpoint:"/individual-discussion-comments-helpful"
  // },
  // {
  //   endpoint:"/individual-discussion"
  // },
  // {
  //   endpoint:"/individual-discussion-tags"
  // },
  // {
  //   endpoint:"/input-positions"
  // },
  // {
  //   endpoint:"/market/components"
  // },
  // {
  //   endpoint:"/market/new_services"
  // },
  // {
  //   endpoint:"/market/popular_services"
  // },
  // {
  //   endpoint:"/market/services"
  // },
  // {
  //   endpoint:"/notifications"
  // },
  // {
  //   endpoint:"/organization/nonMember"
  // },
  // {
  //   endpoint:"/organizations"
  // },
  // {
  //   endpoint:"/popular_discussions"
  // },
  // {
  //   endpoint:"/product/{serviceId}/product_reviews"
  // },
  // {
  //   endpoint:"/product_reviews"
  // },
  // {
  //   endpoint:"/product_reviews_flagged"
  // },
  // {
  //   endpoint:"/product_reviews_helpful"
  // },
  // {
  //   endpoint:"/profile_reviews"
  // },
  // {
  //   endpoint:"/profiles"
  // },
  // {
  //   endpoint:"/review_replies/"
  // },
  // {
  //   endpoint:"/profile_reviews_flagged"
  // },
  // {
  //   endpoint:"/profile_reviews_helpful"
  // },
  // {
  //   endpoint:"/projectJoinApprovalRequests/"
  // },
  // {
  //   endpoint:"/projects"
  // },
  // {
  //   endpoint:"/projects/all"
  // },
  // {
  //   endpoint:"/projects/create"
  // },
  // {
  //   endpoint:"/projects/createWithParameter"
  // },
  // {
  //   endpoint:"/projects_join_requests"
  // },
  // {
  //   endpoint:"/new_members/"
  // },
  // {
  //   endpoint:"/projects_members"
  // },
  // {
  //   endpoint:"/saveprojects_members/"
  // },
  // {
  //   endpoint:"/projects_tags"
  // },
  // {
  //   endpoint:"/resource/assessment"
  // },
  // {
  //   endpoint:"/resource/bay"
  // },
  // {
  //   endpoint:"/resource/course"
  // },
  // {
  //   endpoint:"/resource/job"
  // },
  // {
  //   endpoint:"/resource/lab"
  // },
  // {
  //   endpoint:"/resource/machine"
  // },
  // {
  //   endpoint:"/resource/project"
  // },
  // {
  //   endpoint:"/role/"
  // },
  // {
  //   endpoint:"/search/"
  // },
  // {
  //   endpoint:"/searchCompanies/"
  // },
  // {
  //   endpoint:"/searchComponents/"
  // },
  // {
  //   endpoint:"/searchMembers/"
  // },
  // {
  //   endpoint:"/searchProjects/"
  // },
  // {
  //   endpoint:"/searchServices/"
  // },
  // {
  //   endpoint:"/searchUsers/"
  // },
  // {
  //   endpoint:"/triggerFullIndexing/"
  // },
  // {
  //   endpoint:"/service_authors/service_authors"
  // },
  // {
  //   endpoint:"/array_specifications"
  // },
  // {
  //   endpoint:"/components/"
  // },
  // {
  //   endpoint:"/projects/"
  // },
  // {
  //   endpoint:"/service/"
  // },
  // {
  //   endpoint:"/services"
  // },
  // {
  //   endpoint:"/specifications/"
  // },
  // {
  //   endpoint:"/model_poll/"
  // },
  // {
  //   endpoint:"/model_run"
  // },
  // {
  //   endpoint:"/model_run_file"
  // },
  // {
  //   endpoint:"/model_run_file1"
  // },
  // {
  //   endpoint:"/service_runs"
  // },
  // {
  //   endpoint:"/service_tags"
  // },
  // {
  //   endpoint:"/shared-services"
  // },
  // {
  //   endpoint:"/tags/dmdiiMember"
  // },
  // {
  //   endpoint:"/tags/organization"
  // },
  // {
  //   endpoint:"/tasks"
  // },
  // {
  //   endpoint:"/tasks/create"
  // },
  // {
  //   endpoint:"/user-basic-information"
  // },
  // {
  //   endpoint:"/user"
  // },
  // {
  //   endpoint:"/user/createtoken"
  // },
  // {
  //   endpoint:"/user/organization/"
  // },
  // {
  //   endpoint:"/user/save"
  // },
  // {
  //   endpoint:"/users"
  // },
  // {
  //   endpoint:"/users/create"
  // },
  // {
  //   endpoint:"/userRole"
  // },
  // {
  //   endpoint:"/verify"
  // }
]

var fileContents = JSON.stringify(buildPostmanImport())

fs.writeFile("postman-import.json", fileContents, function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("Write successful");
});
